import React, { useState, useCallback, useEffect } from 'react'
import List from './List';

function Landing() {
  const [number, setNumber] = useState(0);
  const [dark, setDark] = useState(false);
  const [renderCount, setRenderCount] = useState(0);
  const theme = {
    backgroundColor: dark ? '#333' : '#FFF',
    color: dark ? '#FFF' : '#333'
  }
  useEffect(() => {
    setRenderCount(prevRenderCount => prevRenderCount + 1)
  },[])
  const getItems = useCallback(() => ([number, number + 1, number + 2]),[number])
  
  return (
    <div style={theme}>
        <h1>Learn Ctrl</h1>
        <h2></h2>
        <p>
            - Organize your learning <br />
              - Create your syllabus of topics to learn (with suggestions from ChatGPT) <br />
              - Get a lesson generated by ChatGPT on each topic <br />
              - Add extra articles <br />
              - Add notes <br />
              - Browse mentors and industry professionals to check how the pros do it.<br />              
            - Generate lessons with AI edited by humans <br />
            - Check mentors to connect with industry professionals.
        </p>
        <small>Remember to pay attention, hack your learning, and choose topics wisely.</small>
        <input type="number" onChange={e => setNumber(e.target.value)} />
        <div>{number}</div>
        <List getItems={getItems} />
        <button onClick={(number) => setDark(predark => !predark)}>Increment</button>
        <div>{dark}</div>
        <div>Render Count: {renderCount}</div>
    </div>
  )
}

export default Landing