import React from 'react'

function Landing() {
  return (
    <>
        <h1>Learn Ctrl</h1>
        <h2></h2>
        <p>
            - Organize your learning <br />
              - Create your syllabus of topics to learn (with suggestions from ChatGPT) <br />
              - Get a lesson generated by ChatGPT on each topic <br />
              - Add extra articles <br />
              - Add notes <br />
              - Browse mentors and industry professionals to check how the pros do it.<br />              
            - Generate lessons with AI edited by humans <br />
            - Check mentors to connect with industry professionals.
        </p>
        <small>Remember to pay attention, hack your learning, and choose topics wisely.</small>
    </>
  )
}

export default Landing