apiVersion: v1
kind: Service
metadata:
  name: mentor-app-svc
spec:
  selector:
    app: mentor-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31238
  type: NodePort


